name: "FileBrowser"
version: "3.4"
slug: "filebrowser_ha"
description: "FileBrowser su Alpine con password configurabile."
startup: application
arch:
  - aarch64
  - amd64
  - armv7
ports:
  8080/tcp: 8080
map:
  - share:rw
  - media:rw
options:
  root_path: "/share/pubblici"
  admin_password: "admin_password_123" # <--- Valore di default (modificabile da GUI)
schema:
  root_path: str
  admin_password: str                  # <--- Definiamo che è una stringa
init: false
