name: "Dufs File Server"
description: "File server semplice: Download pubblico, Upload privato."
version: "1.03" # Ho alzato la versione
slug: "dufs_server"
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  50000/tcp: 50000
map:
  - share:rw     # Importante: mappa /share
  - media:rw     # AGGIUNTA: mappiamo anche /media, così puoi scegliere di usare quella
options:
  username: "admin"
  password: "cambiami_subito"
  data_path: "/share/pubblici"  # <--- Ecco il valore di default
schema:
  username: str
  password: str
  data_path: str                # <--- Definiamo che è una stringa modificabile
startup: application