name: "Dufs File Server"
description: "File server semplice: Download pubblico, Upload privato."
version: "1.0.0"
slug: "dufs_server"
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  5000/tcp: 5000 # Porta di default esposta
map:
  - share:rw     # Mappa la cartella /share di HA in lettura/scrittura
options:
  username: "admin"
  password: "cambiami_subito"
schema:
  username: str
  password: str
startup: application